### PR TITLE
feat: gentx for Nodeasy.com

### PR DESCRIPTION
**Pull request by sundafa**

### CODE REVIEW

**Comment by angelorc** [comment]
I can't find your registration. Have you filled out the form? https://forms.gle/j7bYDgthCyRdcURWA

**Comment by sundafa** [comment]
> I can't find your registration. Have you filled out the form? https://forms.gle/j7bYDgthCyRdcURWA

Just learned the form, filled it out and submitted it.
I participated in the 2 and 3 testnet, but the form does not have this option

**Comment by angelorc** [comment]
your tx is incompleted, may you missed "}" at end. Could you check it again?

**Comment by sundafa** [comment]
> your tx is incompleted, may you missed "}" at end. Could you check it again?

mail addr: wenzhihao@bitopia.cn
moniker: Nodeasy.com
Address: bitsong1uc2nnuumhn6evhlqpvf3kt27tl7hcv7c9v7xau

**Comment by sundafa** [comment]
I need to resubmit it again

**Comment by sundafa** [comment]
> your tx is incompleted, may you missed "}" at end. Could you check it again?

ok

**Comment by angelorc** [comment]
I'm getting an error
```
panic: unauthorized: signature verification failed; verify correct account sequence and chain-id
```

Could you re-generate your tx?

**Comment by sundafa** [comment]
Regenerated

**Comment by angelorc** [comment]
Same issue. Can you post here the command that you use to generate the tx?

**Comment by sundafa** [comment]
```bitsongd init --chain-id bitsong-testnet-4 Nodeasy.com

bitsongd add-genesis-account $(bitsongcli keys show nodeasy -a) 1000000000ubtsg
bitsongd gentx --name nodeasy --amount 1000000000ubtsg --ip 195.201.159.252```

**Comment by angelorc** [comment]
It's correct. Try this

```
rm -rf ~/.bitsongd
rm -rf ~/.bitsongcli
```
then follow the instructions

**Comment by sundafa** [comment]
Regenerated
I only change the commission

**Comment by angelorc** [comment]
Same issue, it seem an error related to "chain-id"

Which go-bitsong version are you using?

**Comment by sundafa** [comment]
go version 1.15.2
version: 0.6.0-beta1

**Comment by angelorc** [comment]
try with `go 1.13.6`

**Comment by angelorc** [comment]
> Regenerated
> I only change the commission

How do you change the commission?

To change the commission you have to use these flags
```
--commission-max-change-rate string   The maximum commission change rate percentage (per day)
--commission-max-rate string          The maximum commission rate percentage
--commission-rate string              The initial commission rate percentage
```

Example
```
bitsongd gentx --name nodeasy --amount 1000000000ubtsg --ip 195.201.159.252 --commission-rate 0.20
```

**Comment by sundafa** [comment]
I create a new pr
https://github.com/bitsongofficial/networks/pull/122

**Comment by angelorc** [comment]
ok it work!

**Pull request closed without merging**
